### PR TITLE
Countries

### PR DESCRIPTION
**Pull request by dew-dr0p**
## Description

Added Finland flag to the list of country's flags. 

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

No test is required.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by webcrumbs-community** [comment]
Hi! Thanks for that. I merged so I could quickly see it but I think there are few adjustments needed.

Let me show you:

image

image

1. Finland image is not appearing. Perhaps it is because it's using a png image and not an svg, but I don't know.

2. I would start the second line 20px to the right, so that it is centralised.

Tell me what you think.
Cheers!

**Comment by webcrumbs-community** [comment]
Don't worry, @dew-dr0p! I think it's solved for good now. 🙏
Just added a python script at `aux/generate-flags.svg`.

**Comment by dew-dr0p** [comment]
> Don't worry, @dew-dr0p! I think it's solved for good now. 🙏 Just added a Python script at `aux/generate-flags.svg`.

Oh great, so that means no more manual updates of the flags anymore right?
Just running the script should get it done?

Also what was the initial issue, are you clear on why it didn't show, just asking to be sure?

**Comment by webcrumbs-community** [comment]
Yes! Next time we just have to run the script and that's it! 🙌
On the initial issue, all good. Thanks for your help here!

**Pull request merged**
