### PR TITLE
FIX: README.md

### PR DESCRIPTION
**Pull request by itsayopapi**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes # (issue)

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by webcrumbs-community** [comment]
Hi there, @itsayopapi! It's seems to be a conflict of documents. Can you clarify the fix? Tks, mate!

**Comment by itsayopapi** [comment]
@webcrumbs-community 

All fixed now..sorry about that

**Comment by webcrumbs-community** [comment]
Great! Good work

**Comment by webcrumbs-community** [comment]
I gave it a little more of thought and I'm afraid people will get frustrated if we tell them they can install and use webcrumbs it at this moment, since it's not released yet. I'll keep your text saved for the moment we launch the first release. Cheers!

**Comment by itsayopapi** [comment]
I hope I didn't do anything wrong

**Comment by webcrumbs-community** [comment]
No, you didn’t! I saved here and will get it back as soon as we release. :)Em 13 de out. de 2023, à(s) 00:56, Papi ***@***.***> escreveu:﻿
I hope I didn't do anything wrong



On Fri, 13 Oct 2023, 01:24 WebCrumbs Community, ***@***.***>

wrote:

**Comment by itsayopapi** [comment]
Awesome, thank you so much!

**Pull request merged**
