### PR TITLE
working on index page

### PR DESCRIPTION
**Pull request by dshaw0004**
I start working on index page. I am trying to make it like wordpress's landing page.

It is my request to my fellow developers to help me improving this page.

### CODE REVIEW

**Comment by webcrumbs-community** [comment]
Hi, there, @dshaw0004! The front of WebCrumbs is under the /`landing`, which has its own issue. The index of `/admin` is just a boilerplate of the equivalent to the first "blog", if we were Wordpress. So i guess it doesn't need much work on it now. But I'd like to hear your suggestions. Cheers!

**Comment by dshaw0004** [comment]
why are you creating a separate landing page app. The idea behind the landing page should be
 - `/landing` should have the landing page
 - if user is not already logged in then `/` redirect the user to `/landing` or the content of `/` route will be same to `/landing`

**Comment by webcrumbs-community** [comment]
**You're right** we need a landing page more like WordPress. That is being worked under #39 and will be hosted at webcrumbs.org. The structure of the directories **may sound odd** but it is because we will be using microfrontends bundled together with webpack. This is needed for us to install plugins from the admin panel without having to rebuild the code. I hope it will become easier to understand after you check the diagram [here](https://github.com/webcrumbs-community/webcrumbs/wiki/Roadmap). 

I'm closing this for now, but please open a discussion if you have any suggestion for us to discuss in mode detail.
Cheers!

**Comment by webcrumbs-community** [comment]
I'm closing this for now, but please open a discussion if you have any suggestion for us to discuss in mode detail.
Cheers!

**Pull request closed without merging**
